//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalajansBoyaMusteri.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class @default : global::System.Configuration.ApplicationSettingsBase {
        
        private static @default defaultInstance = ((@default)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new @default())));
        
        public static @default Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Canon MF6100 Series UFRII LT")]
        public string VarsayilanYazici {
            get {
                return ((string)(this["VarsayilanYazici"]));
            }
            set {
                this["VarsayilanYazici"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Print to PDF")]
        public string BarkodYazici {
            get {
                return ((string)(this["BarkodYazici"]));
            }
            set {
                this["BarkodYazici"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USB 2.0 PC CAMERA,0")]
        public string KameraAygiti {
            get {
                return ((string)(this["KameraAygiti"]));
            }
            set {
                this["KameraAygiti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public string Versiyon {
            get {
                return ((string)(this["Versiyon"]));
            }
            set {
                this["Versiyon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool YaziciIlkSayfa {
            get {
                return ((bool)(this["YaziciIlkSayfa"]));
            }
            set {
                this["YaziciIlkSayfa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OtomatikGirisSayfasi {
            get {
                return ((bool)(this["OtomatikGirisSayfasi"]));
            }
            set {
                this["OtomatikGirisSayfasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OtomatikBarkodEtiketi {
            get {
                return ((bool)(this["OtomatikBarkodEtiketi"]));
            }
            set {
                this["OtomatikBarkodEtiketi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hepsi")]
        public string OtomatikPaket {
            get {
                return ((string)(this["OtomatikPaket"]));
            }
            set {
                this["OtomatikPaket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KameraCozunurluk {
            get {
                return ((int)(this["KameraCozunurluk"]));
            }
            set {
                this["KameraCozunurluk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OtomatikYapilanTestler {
            get {
                return ((bool)(this["OtomatikYapilanTestler"]));
            }
            set {
                this["OtomatikYapilanTestler"] = value;
            }
        }
    }
}
