//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalajansBoyaMusteri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisanlar
    {
        public int CalisanID { get; set; }
        public string calisanad { get; set; }
        public string calisansoyad { get; set; }
        public string calisantel { get; set; }
        public string calisanmaas { get; set; }
    }
}
