//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalajansBoyaMusteri
{
    using System;
    using System.Collections.Generic;
    
    public partial class lisans
    {
        public string LisansID { get; set; }
        public string LisansSahibi { get; set; }
        public string LisansFirmasi { get; set; }
        public string LisansKey { get; set; }
        public Nullable<System.DateTime> LisansTarihi { get; set; }
        public string KayitTarihi { get; set; }
    }
}
