//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalajansBoyaMusteri
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteri
    {
        public int MusteriID { get; set; }
        public string musteriadi { get; set; }
        public string musterisoyadi { get; set; }
        public string musteritelefon { get; set; }
        public string aracadi { get; set; }
        public string aracmarkasi { get; set; }
        public string aracmodeli { get; set; }
        public string aracplakasi { get; set; }
        public string arackmsi { get; set; }
        public string aracrenk { get; set; }
        public string aractestturu { get; set; }
        public string aractestsonucu { get; set; }
        public Nullable<decimal> aracyedekparcaucreti { get; set; }
        public Nullable<decimal> aracservisucreti { get; set; }
        public string aracdigerucretnedeni { get; set; }
        public Nullable<decimal> aracdigerucretler { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
