//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalajansBoyaMusteri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevular
    {
        public int id { get; set; }
        public string MusteriAdsoyad { get; set; }
        public string MusteriTelefonu { get; set; }
        public string RandevuTarihi { get; set; }
        public string Mesaj { get; set; }
        public Nullable<System.DateTime> islemTarihi { get; set; }
        public string RandevuKodu { get; set; }
        public string Şube { get; set; }
    }
}
