//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalajansBoyaMusteri
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MUSTERILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MUSTERILER()
        {
            this.TBL_FK = new HashSet<TBL_FK>();
            this.TBL_ODEMELER = new HashSet<TBL_ODEMELER>();
        }
    
        public int MusteriID { get; set; }
        public string BarkodNo { get; set; }
        public string AliciAdsoyad { get; set; }
        public string AliciEmail { get; set; }
        public string AliciTelefon { get; set; }
        public string SaticiAdsoyad { get; set; }
        public string SaticiıEmail { get; set; }
        public string SaticiTelefon { get; set; }
        public string AliciTcNo { get; set; }
        public string SaticiTcNo { get; set; }
        public string PaketAdi { get; set; }
        public string PaketIcerik { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_FK> TBL_FK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ODEMELER> TBL_ODEMELER { get; set; }
    }
}
