//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalajansBoyaMusteri
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BOYADEGERLERI
    {
        public int id { get; set; }
        public string Value { get; set; }
        public string Deger { get; set; }
        public Nullable<int> SiraNo { get; set; }
    }
}
