//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalajansBoyaMusteri
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FirmaPCKeys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_FirmaPCKeys()
        {
            this.TBL_Firma_FK = new HashSet<TBL_Firma_FK>();
        }
    
        public int LisansID { get; set; }
        public string CPUID { get; set; }
        public string HDDSerial { get; set; }
        public string AnakartSerial { get; set; }
        public string MacAdress { get; set; }
        public string RegeditKey { get; set; }
        public string LisansNo { get; set; }
        public string LisansSifresi { get; set; }
        public Nullable<int> LisansHakki { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Firma_FK> TBL_Firma_FK { get; set; }
    }
}
