//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalajansBoyaMusteri
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MUSTERIARACLARI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MUSTERIARACLARI()
        {
            this.TBL_FK = new HashSet<TBL_FK>();
            this.TBL_ODEMELER = new HashSet<TBL_ODEMELER>();
        }
    
        public int AracID { get; set; }
        public Nullable<int> MarkaID { get; set; }
        public Nullable<int> BoyaDegisenID { get; set; }
        public string MarkaveTip { get; set; }
        public string AltTipi { get; set; }
        public string Plaka { get; set; }
        public string ModelYili { get; set; }
        public string Renk { get; set; }
        public string Km { get; set; }
        public string SasiNo { get; set; }
        public string MotorNo { get; set; }
        public string KaskoVarmi { get; set; }
        public string SigortaTeklfi { get; set; }
        public string YakitTipi { get; set; }
        public string VitesTipi { get; set; }
        public string MuayeneTarihi { get; set; }
        public string EgsızMuayeneTarihi { get; set; }
        public string KullanimTuru { get; set; }
        public string KullanimKasaTipi { get; set; }
        public string KullanimAltTipi { get; set; }
        public string BoyaRaporPath { get; set; }
    
        public virtual TBL_ARACBOYASONUC TBL_ARACBOYASONUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_FK> TBL_FK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ODEMELER> TBL_ODEMELER { get; set; }
    }
}
