//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalajansBoyaMusteri
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BOYAKONUMLARI
    {
        public int id { get; set; }
        public string AracTipi { get; set; }
        public string KonumAdi { get; set; }
        public string KonumX { get; set; }
        public string KonumY { get; set; }
    }
}
