//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalajansBoyaMusteri
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebBoyaRapor
    {
        public int id { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public string SolOnCamurluk { get; set; }
        public string SagOnCamurluk { get; set; }
        public string SolOnKapi { get; set; }
        public string SagOnKapi { get; set; }
        public string SolArkaKapi { get; set; }
        public string SagArkaKapi { get; set; }
        public string SolArkaCamurluk { get; set; }
        public string SagArkaCamurluk { get; set; }
        public string Kaput { get; set; }
        public string Tavan { get; set; }
        public string Bagaj { get; set; }
        public string MusteriAdiSoyadi { get; set; }
        public string MusteriPlaka { get; set; }
        public string MusteriAracMarkaModel { get; set; }
    }
}
