//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalajansBoyaMusteri
{
    using System;
    using System.Collections.Generic;
    
    public partial class yedekparcalistesi
    {
        public int YedekParcaID { get; set; }
        public Nullable<int> YedekSubID { get; set; }
        public string yedekparcaadi { get; set; }
        public Nullable<int> yedekparcaadeti { get; set; }
        public string yedekparcafirmasi { get; set; }
        public Nullable<int> yedekparcaucret { get; set; }
        public string tornafirmasi { get; set; }
        public Nullable<int> tornaucreti { get; set; }
        public Nullable<int> iscilikucreti { get; set; }
        public string yparcaraporu { get; set; }
    }
}
